# Generated by Django 4.0.3 on 2022-11-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Div',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='內容')),
                ('status', models.BooleanField(default=False, verbose_name='狀態')),
                ('divnumber', models.IntegerField(default=0, verbose_name='編號')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='內容')),
                ('status', models.BooleanField(default=False, verbose_name='狀態')),
                ('div', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='web.div')),
            ],
        ),
    ]
